apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mychart.fullname" . }}-cron
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron
              image: "{{ .Values.cron.image }}"
              command: {{ toJson .Values.cron.command }}
