apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "mychart.fullname" . }}-daemon
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: daemon
  template:
    metadata:
      labels:
        app.kubernetes.io/component: daemon
    spec:
      containers:
        - name: daemon
          image: "{{ .Values.daemon.image }}"
          command: {{ toJson .Values.daemon.command }}
